[package]
name = "axum-post-example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["http2", "macros"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
